[dhall]
git-tree-sha1 = "f296f1c3f770aaade98d2f1dfa960c89dee06318"
lazy = true

    [[dhall.download]]
    sha256 = "79b121880de426ef6a7ffd665e0754c5ad71871d"
    url = "https://github.com/dhall-lang/dhall-haskell/releases/download/1.30.0/dhall-1.30.0-x86_64-linux.tar.bz2"

[dhall-json]
git-tree-sha1 = "07ab24141dc6e00acc202049313add93edaa414f"
lazy = true

    [[dhall-json.download]]
    sha256 = "c747c3fd7ae79aac1a758e617098378b0f1bb0ba"
    url = "https://github.com/dhall-lang/dhall-haskell/releases/download/1.30.0/dhall-json-1.6.2-x86_64-linux.tar.bz2"

[dhall-yaml]
git-tree-sha1 = "216f8d6a04d1b99612ec23f55ea3c82d64e36e84"
lazy = true

    [[dhall-yaml.download]]
    sha256 = "f112a22ac63a0c16ed2c7141e57658b8a2df1a1e"
    url = "https://github.com/dhall-lang/dhall-haskell/releases/download/1.30.0/dhall-yaml-1.0.2-x86_64-linux.tar.bz2"
